version: '3.8'

services:
  magicshell:
    build: .
    image: ghcr.io/ericzarnosky/magicshell:latest
    container_name: ${CONTAINER_NAME:-magicshell}
    hostname: ${HOSTNAME:-MagicShell}
    restart: unless-stopped
    
    # Privileged mode for NFS/SMB mounting and Tailscale
    privileged: true
    
    # Network configuration
    network_mode: host
    
    # Environment variables
    environment:
      - PASSWORD=${PASSWORD:-password}
      - PASSWORD_FILE=${PASSWORD_FILE:-}
      - TZ=${TZ:-UTC}
      - SHELL=${SHELL:-bash}
      - HOSTNAME=${HOSTNAME:-MagicShell}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - ENABLE_TAILSCALE=${ENABLE_TAILSCALE:-false}
    
    # Volume mounts
    volumes:
      # Root home directory persistence
      - ./config:/root/config
      
      # fstab persistence
      - ./config/fstab:/etc/fstab:ro
      
      # Docker socket (optional, for Docker-in-Docker scenarios)
      # - /var/run/docker.sock:/var/run/docker.sock
      
      # Tailscale socket (if running Tailscale on host)
      # - /var/run/tailscale:/var/run/tailscale
    
    # Exposed ports
    ports:
      - "${SSH_PORT:-2222}:22"
    
    # Secrets (uncomment to use password file)
    # secrets:
    #   - root_password
    
    # Capabilities
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - DAC_READ_SEARCH
    
    # Device access for NFS/SMB
    devices:
      - /dev/fuse

# Uncomment to use Docker secrets for password
# secrets:
#   root_password:
#     file: ./secrets/root_password.txt