version: '3.8'

services:
  magicshell:
    build: .
    image: ghcr.io/ericzarnosky/magicshell:latest
    container_name: ${CONTAINER_NAME:-magicshell}
    hostname: ${HOSTNAME:-MagicShell}
    restart: unless-stopped
    
    # Privileged mode for NFS/SMB mounting and network configuration
    privileged: true
    
    # Network configuration
    network_mode: host
    
    # Environment variables
    environment:
      - PASSWORD=${PASSWORD:-password}
      - PASSWORD_FILE=${PASSWORD_FILE:-}
      - TZ=${TZ:-UTC}
      - SHELL=${SHELL:-bash}
      - HOSTNAME=${HOSTNAME:-MagicShell}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - ENABLE_TAILSCALE=${ENABLE_TAILSCALE:-false}
      # Network configuration
      - MAC=${MAC:-0D:EC:AF:C0:FF:EE}
      - IP_ADDRESS=${IP_ADDRESS:-}
      - IP_ADDRESS6=${IP_ADDRESS6:-}
      - IP_GATEWAY=${IP_GATEWAY:-}
      - IP_GATEWAY6=${IP_GATEWAY6:-}
      - IP_DNS=${IP_DNS:-}
      - IP_DNS6=${IP_DNS6:-}
      # SSH configuration
      - SSH_PORT=${SSH_PORT:-2222}
    
    # Volume mounts
    volumes:
      # Root home directory persistence
      - ./config:/root/config
      
      # fstab persistence
      - ./config/fstab:/etc/fstab:ro
      
      # Docker socket (optional, for Docker-in-Docker scenarios)
      # - /var/run/docker.sock:/var/run/docker.sock
      
      # Tailscale socket (if running Tailscale on host)
      # - /var/run/tailscale:/var/run/tailscale
    
    # Exposed ports - SSH port is now configurable
    ports:
      - "${SSH_PORT:-2222}:${SSH_PORT:-2222}"
    
    # Secrets (uncomment to use password file)
    # secrets:
    #   - root_password
    
    # Capabilities
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - DAC_READ_SEARCH
      - NET_RAW  # Required for network configuration
    
    # Device access for NFS/SMB
    devices:
      - /dev/fuse

# Uncomment to use Docker secrets for password
# secrets:
#   root_password:
#     file: ./secrets/root_password.txtd:
#     file: ./secrets/root_password.txt